FROM wordpress:6.6.1-php8.3-apache

RUN apt-get update && \
	apt-get install -y  --no-install-recommends ssl-cert && \
	rm -r /var/lib/apt/lists/* && \
	a2enmod ssl rewrite expires && \
	a2ensite default-ssl && \
    apt-get update && apt install -y mariadb-client

ENV PHP_INI_PATH "/usr/local/etc/php/php.ini"

RUN pecl install xdebug && docker-php-ext-enable xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_port=9000" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_enable=1" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_connect_back=0" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_host=docker.for.mac.localhost" >> ${PHP_INI_PATH} \
    && echo "xdebug.idekey=IDEA_DEBUG" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_autostart=1" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_log=/tmp/xdebug.log" >> ${PHP_INI_PATH}
RUN echo "Mutex posixsem" >> /etc/apache2/apache2.conf

RUN curl -o /usr/local/bin/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
COPY ./wpcli-user.sh /usr/local/bin/wp
COPY ./wp-install.sh /usr/local/bin/wp-install.sh
COPY ./sync-plugin.sh /usr/local/bin/sync-plugin.sh
RUN chmod +x /usr/local/bin/wp
RUN chmod +x /usr/local/bin/wp-cli.phar
RUN chmod +x /usr/local/bin/wp-install.sh
RUN chmod +x /usr/local/bin/sync-plugin.sh
CMD /usr/local/bin/wp-install.sh

EXPOSE 80
EXPOSE 443
