<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'bmltintegration' => '/../../admin/bmlt_integration.php',
                'wbw_submissions_rest' => '/../../admin/admin_rest_controller.php',
                'wbw_submissions_rest_handlers' => '/../../admin/admin_rest_handlers.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
